### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by litong-2017** [GopherCoder/FIFA-World-Cup#1]
go run main.go
# command-line-arguments
.\main.go:63:16: undefined: config
.\main.go:64:19: undefined: download
.\main.go:65:2: undefined: domain
.\main.go:69:14: undefined: config
.\main.go:70:17: undefined: download
.\main.go:71:2: undefined: domain
.\main.go:75:15: undefined: config
.\main.go:76:18: undefined: download
.\main.go:77:2: undefined: domain
.\main.go:81:16: undefined: config
.\main.go:81:16: too many errors

**Comment by wuxiaoxiaoshen** [comment]
1. 使用pg 数据库创建数据库fifaworldcupcopy（使用docker 也行）
2. make install 安装依赖
3. make dev 启动服务

**Comment by XieWeiXie** [comment]
> go run main.go
> 
> # command-line-arguments
> .\main.go:63:16: undefined: config
> .\main.go:64:19: undefined: download
> .\main.go:65:2: undefined: domain
> .\main.go:69:14: undefined: config
> .\main.go:70:17: undefined: download
> .\main.go:71:2: undefined: domain
> .\main.go:75:15: undefined: config
> .\main.go:76:18: undefined: download
> .\main.go:77:2: undefined: domain
> .\main.go:81:16: undefined: config
> .\main.go:81:16: too many errors
1. 使用pg 数据库创建数据库fifaworldcupcopy（使用docker 也行）
2. make install 安装依赖
3. make dev 启动服务

docker 启动pg 数据库教程：https://hub.docker.com/_/postgres/
